// Code generated by gorr-codegen. DO NOT EDIT.

package gorr

import "fmt"

// ExprKind represents the kind of a class expression in the OWL EL fragment.
type ExprKind uint8

const (
	ExprClass ExprKind = iota
	ExprObjectIntersectionOf
	ExprObjectUnionOf
	ExprObjectSomeValuesFrom
	ExprObjectHasSelf
	ExprObjectOneOf
	ExprObjectProperty
	ExprDataProperty
	ExprInverseObjectProperty
)

// String returns the name of the expression kind.
func (e ExprKind) String() string {
	switch e {
	case ExprClass:
		return "Class"
	case ExprObjectIntersectionOf:
		return "ObjectIntersectionOf"
	case ExprObjectUnionOf:
		return "ObjectUnionOf"
	case ExprObjectSomeValuesFrom:
		return "ObjectSomeValuesFrom"
	case ExprObjectHasSelf:
		return "ObjectHasSelf"
	case ExprObjectOneOf:
		return "ObjectOneOf"
	case ExprObjectProperty:
		return "ObjectProperty"
	case ExprDataProperty:
		return "DataProperty"
	case ExprInverseObjectProperty:
		return "InverseObjectProperty"
	default:
		return "Unknown"
	}
}

// IsClassExpr returns true if this is a class expression kind.
func (e ExprKind) IsClassExpr() bool {
	return e >= ExprClass && e <= ExprDataProperty
}

// ClassExprKind returns the ExprKind as a string for use in type switches.
func (e ExprKind) ClassExprKind() string {
	return e.String()
}

// ConclusionKind represents the kind of a conclusion in the saturation state.
type ConclusionKind uint8

const (
	ConclusionSubsumerC ConclusionKind = iota
	ConclusionSubsumerD
	ConclusionForwardLink
	ConclusionBackwardLink
	ConclusionDisjointness
	ConclusionPropagation
	ConclusionInconsistency
)

// String returns the name of the conclusion kind.
func (c ConclusionKind) String() string {
	switch c {
	case ConclusionSubsumerC:
		return "SubsumerC"
	case ConclusionSubsumerD:
		return "SubsumerD"
	case ConclusionForwardLink:
		return "ForwardLink"
	case ConclusionBackwardLink:
		return "BackwardLink"
	case ConclusionDisjointness:
		return "Disjointness"
	case ConclusionPropagation:
		return "Propagation"
	case ConclusionInconsistency:
		return "Inconsistency"
	default:
		return "Unknown"
	}
}

// IsSubsumption returns true if this conclusion kind represents a subsumption.
func (c ConclusionKind) IsSubsumption() bool {
	return c == ConclusionSubsumerC || c == ConclusionSubsumerD
}

// Conclusion represents a derived conclusion in a context.
type Conclusion struct {
	Kind   ConclusionKind
	Root   Handle
	Target Handle
}

// String returns a string representation of the conclusion.
func (c Conclusion) String() string {
	switch c.Kind {
	case ConclusionSubsumerC, ConclusionSubsumerD:
		return fmt.Sprintf("%v(%v ⊑ %v)", c.Kind, c.Root, c.Target)
	case ConclusionForwardLink:
		return fmt.Sprintf("ForwardLink(%v ->%v %v)", c.Root, c.Target, c.Root)
	case ConclusionBackwardLink:
		return fmt.Sprintf("BackwardLink(%v <-%v %v)", c.Root, c.Target, c.Target)
	default:
		return fmt.Sprintf("%v(%v, %v)", c.Kind, c.Root, c.Target)
	}
}

// Handle is a dense uint32 reference to an indexed object.
type Handle uint32

const (
	// HandleBottom represents owl:Nothing (the unsatisfiable class)
	HandleBottom Handle = 0
	// HandleTop represents owl:Thing (the top class)
	HandleTop Handle = 1
	// HandleMin is the minimum user-assignable handle
	HandleMin Handle = 2
)

// HandleSet is a set of handles with hybrid storage (small = sorted slice, large = map).
type HandleSet struct {
	small []Handle
	large map[Handle]struct{}
}

// NewHandleSet creates a new empty handle set.
func NewHandleSet() *HandleSet {
	return &HandleSet{}
}

// Add adds a handle to the set. Returns true if the handle was newly added.
func (s *HandleSet) Add(h Handle) bool {
	if len(s.small) < 16 {
		for _, existing := range s.small {
			if existing == h {
				return false
			}
		}
		s.small = append(s.small, h)
		sortHandles(s.small)
		return true
	}
	if s.large == nil {
		s.large = make(map[Handle]struct{})
		for _, h := range s.small {
			s.large[h] = struct{}{}
		}
		s.small = nil
	}
	if _, ok := s.large[h]; ok {
		return false
	}
	s.large[h] = struct{}{}
	return true
}

// Contains returns true if the handle is in the set.
func (s *HandleSet) Contains(h Handle) bool {
	if s.large != nil {
		_, ok := s.large[h]
		return ok
	}
	for _, eh := range s.small {
		if eh == h {
			return true
		}
	}
	return false
}

// Size returns the number of handles in the set.
func (s *HandleSet) Size() int {
	if s.large != nil {
		return len(s.large)
	}
	return len(s.small)
}

// Iterate calls fn for each handle in the set.
func (s *HandleSet) Iterate(fn func(Handle)) {
	if s.large != nil {
		for h := range s.large {
			fn(h)
		}
		return
	}
	for _, h := range s.small {
		fn(h)
	}
}

// ToSlice returns all handles as a slice.
func (s *HandleSet) ToSlice() []Handle {
	if s.large != nil {
		result := make([]Handle, 0, len(s.large))
		for h := range s.large {
			result = append(result, h)
		}
		return result
	}
	result := make([]Handle, len(s.small))
	copy(result, s.small)
	return result
}

func sortHandles(h []Handle) {
	for i := 1; i < len(h); i++ {
		if h[i] < h[i-1] {
			h[i], h[i-1] = h[i-1], h[i]
			i = 0
		}
	}
}

// Inference represents an inference step with a conclusion and premises.
type Inference struct {
	Conclusion Conclusion
	Premises   []Conclusion
	Name       string
}

// Producer is a function that produces conclusions.
type Producer func(Conclusion)

// Rule applies a premise to a context and produces conclusions.
type Rule func(premise Conclusion, ctx *Context, produce Producer)

// RuleTable is a dispatch table for rules keyed by conclusion kind.
type RuleTable map[ConclusionKind][]Rule

// NewRuleTable creates a new empty rule table.
func NewRuleTable() RuleTable {
	return make(RuleTable)
}

// Register adds a rule for a conclusion kind.
func (t RuleTable) Register(kind ConclusionKind, rule Rule) {
	t[kind] = append(t[kind], rule)
}

// Rules returns the rules for a conclusion kind.
func (t RuleTable) Rules(kind ConclusionKind) []Rule {
	return t[kind]
}

// InferenceType constants for proof reconstruction.
const (
	InferenceToldSubsumption          = "ToldSubsumption"
	InferenceConjunctionDecomposition = "ConjunctionDecomposition"
	InferenceConjunctionComposition   = "ConjunctionComposition"
	InferenceExistentialDecomposition = "ExistentialDecomposition"
	InferenceExistentialComposition   = "ExistentialComposition"
	InferenceRoleHierarchy            = "RoleHierarchy"
	InferenceRoleChain                = "RoleChain"
	InferenceDisjointInference        = "DisjointInference"
	InferenceSelfInference            = "SelfInference"
	InferenceRangeInference           = "RangeInference"
	InferenceAxiomConversion          = "AxiomConversion"
)

// Rule numbers for the EL+⊥ calculus.
const (
	RuleInit                     = 1
	RuleInitTop                  = 2
	RuleToldExpansion            = 3
	RuleConjunctionDecomposition = 4
	RuleConjunctionComposition   = 5
	RuleExistentialDecomposition = 6
	RuleExistentialComposition   = 7
	RuleRoleHierarchy            = 8
	RuleRoleChain                = 9
	RuleBottom                   = 10
	RuleDisjointness             = 11
	RuleHasSelf                  = 12
	RuleRange                    = 13
)

// RuleNames returns human-readable names for rule numbers.
func RuleNames() map[int]string {
	return map[int]string{
		RuleInit:                     "Init",
		RuleInitTop:                  "InitTop",
		RuleToldExpansion:            "ToldExpansion",
		RuleConjunctionDecomposition: "ConjunctionDecomposition",
		RuleConjunctionComposition:   "ConjunctionComposition",
		RuleExistentialDecomposition: "ExistentialDecomposition",
		RuleExistentialComposition:   "ExistentialComposition",
		RuleRoleHierarchy:            "RoleHierarchy",
		RuleRoleChain:                "RoleChain",
		RuleBottom:                   "Bottom",
		RuleDisjointness:             "Disjointness",
		RuleHasSelf:                  "HasSelf",
		RuleRange:                    "Range",
	}
}
