package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"path/filepath"
	"text/template"
)

var (
	specFile    string
	outputFile  string
	packageName string
)

func init() {
	flag.StringVar(&specFile, "spec", "calculus.json", "Path to calculus spec JSON file")
	flag.StringVar(&outputFile, "output", "generated.go", "Output file for generated code")
	flag.StringVar(&packageName, "package", "gorr", "Package name for generated code")
	flag.Parse()
}

type ExprKind struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Arguments   []string `json:"arguments,omitempty"`
}

type ConclusionKind struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type InferenceType struct {
	Name       string   `json:"name"`
	Conclusion string   `json:"conclusion"`
	Premises   []string `json:"premises"`
}

type RuleDef struct {
	Name       string `json:"name"`
	Number     int    `json:"number"`
	Conclusion string `json:"conclusion"`
	Premises   string `json:"premises"`
}

type CalculusSpec struct {
	ExprKinds       []ExprKind       `json:"expr_kinds"`
	ConclusionKinds []ConclusionKind `json:"conclusion_kinds"`
	InferenceTypes  []InferenceType  `json:"inference_types"`
	Rules           []RuleDef        `json:"rules"`
}

func main() {
	specPath := specFile
	if !filepath.IsAbs(specPath) {
		wd, _ := os.Getwd()
		specPath = filepath.Join(wd, specPath)
	}

	data, err := os.ReadFile(specPath)
	if err != nil {
		log.Fatalf("Failed to read spec file: %v", err)
	}

	var spec CalculusSpec
	if err := json.Unmarshal(data, &spec); err != nil {
		log.Fatalf("Failed to parse spec JSON: %v", err)
	}

	var buf bytes.Buffer
	if err := generateCode(&buf, &spec); err != nil {
		log.Fatalf("Failed to generate code: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("Warning: Failed to format generated code: %v", err)
		formatted = buf.Bytes()
	}

	outPath := outputFile
	if !filepath.IsAbs(outPath) {
		wd, _ := os.Getwd()
		outPath = filepath.Join(wd, outPath)
	}

	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		log.Fatalf("Failed to write output: %v", err)
	}

	fmt.Printf("Generated %s from %s\n", outPath, specPath)
}

var codeTemplate = template.Must(template.New("code").Parse(`// Code generated by gorr-codegen. DO NOT EDIT.

package {{.Package}}

import "fmt"

// ExprKind represents the kind of a class expression in the OWL EL fragment.
type ExprKind uint8

const (
	ExprClass ExprKind = iota
	ExprObjectIntersectionOf
	ExprObjectUnionOf
	ExprObjectSomeValuesFrom
	ExprObjectHasSelf
	ExprObjectOneOf
	ExprObjectProperty
	ExprDataProperty
	ExprInverseObjectProperty
)

// String returns the name of the expression kind.
func (e ExprKind) String() string {
	switch e {
	{{- range .ExprKinds}}
	case Expr{{.Name}}:
		return "{{.Name}}"
	{{- end}}
	default:
		return "Unknown"
	}
}

// IsClassExpr returns true if this is a class expression kind.
func (e ExprKind) IsClassExpr() bool {
	return e >= ExprClass && e <= ExprDataProperty
}

{{if .ExprKinds}}
// ClassExprKind returns the ExprKind as a string for use in type switches.
func (e ExprKind) ClassExprKind() string {
	return e.String()
}
{{end}}

// ConclusionKind represents the kind of a conclusion in the saturation state.
type ConclusionKind uint8

const (
	ConclusionSubsumerC ConclusionKind = iota
	ConclusionSubsumerD
	ConclusionForwardLink
	ConclusionBackwardLink
	ConclusionDisjointness
	ConclusionPropagation
	ConclusionInconsistency
)

// String returns the name of the conclusion kind.
func (c ConclusionKind) String() string {
	switch c {
	{{- range .ConclusionKinds}}
	case Conclusion{{.Name}}:
		return "{{.Name}}"
	{{- end}}
	default:
		return "Unknown"
	}
}

// IsSubsumption returns true if this conclusion kind represents a subsumption.
func (c ConclusionKind) IsSubsumption() bool {
	return c == ConclusionSubsumerC || c == ConclusionSubsumerD
}

// Conclusion represents a derived conclusion in a context.
type Conclusion struct {
	Kind    ConclusionKind
	Root   Handle
	Target Handle
}

// String returns a string representation of the conclusion.
func (c Conclusion) String() string {
	switch c.Kind {
	case ConclusionSubsumerC, ConclusionSubsumerD:
		return fmt.Sprintf("%v(%v ⊑ %v)", c.Kind, c.Root, c.Target)
	case ConclusionForwardLink:
		return fmt.Sprintf("ForwardLink(%v ->%v %v)", c.Root, c.Target, c.Root)
	case ConclusionBackwardLink:
		return fmt.Sprintf("BackwardLink(%v <-%v %v)", c.Root, c.Target, c.Target)
	default:
		return fmt.Sprintf("%v(%v, %v)", c.Kind, c.Root, c.Target)
	}
}

// Handle is a dense uint32 reference to an indexed object.
type Handle uint32

const (
	// HandleBottom represents owl:Nothing (the unsatisfiable class)
	HandleBottom Handle = 0
	// HandleTop represents owl:Thing (the top class)
	HandleTop Handle = 1
	// HandleMin is the minimum user-assignable handle
	HandleMin Handle = 2
)

// HandleSet is a set of handles with hybrid storage (small = sorted slice, large = map).
type HandleSet struct {
	small []Handle
	large map[Handle]struct{}
}

// NewHandleSet creates a new empty handle set.
func NewHandleSet() *HandleSet {
	return &HandleSet{}
}

// Add adds a handle to the set. Returns true if the handle was newly added.
func (s *HandleSet) Add(h Handle) bool {
	if len(s.small) < 16 {
		for _, existing := range s.small {
			if existing == h {
				return false
			}
		}
		s.small = append(s.small, h)
		sortHandles(s.small)
		return true
	}
	if s.large == nil {
		s.large = make(map[Handle]struct{})
		for _, h := range s.small {
			s.large[h] = struct{}{}
		}
		s.small = nil
	}
	if _, ok := s.large[h]; ok {
		return false
	}
	s.large[h] = struct{}{}
	return true
}

// Contains returns true if the handle is in the set.
func (s *HandleSet) Contains(h Handle) bool {
	if s.large != nil {
		_, ok := s.large[h]
		return ok
	}
	for _, eh := range s.small {
		if eh == h {
			return true
		}
	}
	return false
}

// Size returns the number of handles in the set.
func (s *HandleSet) Size() int {
	if s.large != nil {
		return len(s.large)
	}
	return len(s.small)
}

// Iterate calls fn for each handle in the set.
func (s *HandleSet) Iterate(fn func(Handle)) {
	if s.large != nil {
		for h := range s.large {
			fn(h)
		}
		return
	}
	for _, h := range s.small {
		fn(h)
	}
}

// ToSlice returns all handles as a slice.
func (s *HandleSet) ToSlice() []Handle {
	if s.large != nil {
		result := make([]Handle, 0, len(s.large))
		for h := range s.large {
			result = append(result, h)
		}
		return result
	}
	result := make([]Handle, len(s.small))
	copy(result, s.small)
	return result
}

func sortHandles(h []Handle) {
	for i := 1; i < len(h); i++ {
		if h[i] < h[i-1] {
			h[i], h[i-1] = h[i-1], h[i]
			i = 0
		}
	}
}

// Inference represents an inference step with a conclusion and premises.
type Inference struct {
	Conclusion Conclusion
	Premises   []Conclusion
	Name       string
}

// Producer is a function that produces conclusions.
type Producer func(Conclusion)

// Rule applies a premise to a context and produces conclusions.
type Rule func(premise Conclusion, ctx *Context, produce Producer)

// RuleTable is a dispatch table for rules keyed by conclusion kind.
type RuleTable map[ConclusionKind][]Rule

// NewRuleTable creates a new empty rule table.
func NewRuleTable() RuleTable {
	return make(RuleTable)
}

// Register adds a rule for a conclusion kind.
func (t RuleTable) Register(kind ConclusionKind, rule Rule) {
	t[kind] = append(t[kind], rule)
}

// Rules returns the rules for a conclusion kind.
func (t RuleTable) Rules(kind ConclusionKind) []Rule {
	return t[kind]
}

// InferenceType constants for proof reconstruction.
const (
	{{- range .InferenceTypes}}
	Inference{{.Name}} = "{{.Name}}"
	{{- end}}
)

// Rule numbers for the EL+⊥ calculus.
const (
	{{- range .Rules}}
	Rule{{.Name}} = {{.Number}}
	{{- end}}
)

// RuleNames returns human-readable names for rule numbers.
func RuleNames() map[int]string {
	return map[int]string{
		{{- range .Rules}}
		Rule{{.Name}}: "{{.Name}}",
		{{- end}}
	}
}
`))

func generateCode(w io.Writer, spec *CalculusSpec) error {
	data := map[string]interface{}{
		"Package":         packageName,
		"ExprKinds":       spec.ExprKinds,
		"ConclusionKinds": spec.ConclusionKinds,
		"InferenceTypes":  spec.InferenceTypes,
		"Rules":           spec.Rules,
	}
	return codeTemplate.Execute(w, data)
}
